import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

/**
 * Schema additions for Wikipefia Chat:
 *
 * - `threadMeta` — app-specific metadata for chat threads layered on top of
 *   what @convex-dev/agent stores: model id, system prompt version,
 *   soft-delete, cancel flag, unlocked widgets for tiered tool disclosure.
 *
 * The @convex-dev/agent component manages its own internal tables for
 * threads, messages, and stream deltas via the registered component — we
 * don't define those here.
 *
 * `userId` is the anonymous session id from the client (stored in
 * localStorage). It scopes a user's threads to their browser/device. There
 * is no auth — this is a v1 simplification; auth can be added later.
 */
export default defineSchema({
  // Existing app: projects (Wikipefia studio content registry)
  projects: defineTable({
    slug: v.string(),
    name: v.string(),
    description: v.string(),
    githubRepo: v.string(),
    branch: v.string(),
    type: v.union(
      v.literal("subject"),
      v.literal("teacher"),
      v.literal("system"),
    ),
    configJson: v.optional(v.any()),
    cachedTree: v.optional(
      v.array(
        v.object({
          path: v.string(),
          type: v.string(),
          sha: v.string(),
          size: v.optional(v.number()),
        }),
      ),
    ),
    lastSynced: v.optional(v.number()),
  })
    .index("by_slug", ["slug"])
    .index("by_type", ["type"])
    .index("by_github_repo", ["githubRepo"]),

  // Chat: per-thread metadata layered on top of @convex-dev/agent's threads
  threadMeta: defineTable({
    /** Foreign reference to the agent component's thread id (a string). */
    threadId: v.string(),
    /** Anonymous session id from the client (localStorage-stored UUID). */
    userId: v.string(),
    /** Display title — generated from first user message. */
    title: v.string(),
    /** Lifecycle status (UI hint). */
    status: v.union(
      v.literal("idle"),
      v.literal("generating"),
      v.literal("awaiting_user"),
      v.literal("error"),
    ),
    /** OpenRouter model id locked at thread creation. */
    modelId: v.string(),
    /** System prompt version used for this thread (for replay/debug). */
    systemPromptVersion: v.string(),
    /** Set by cancelGeneration mutation; checked by agent step to abort. */
    cancelRequested: v.boolean(),
    /** Soft-delete timestamp. */
    deletedAt: v.optional(v.number()),
    /** Widget names the model has unlocked via lookupWidgetDocs in this thread. */
    unlockedWidgets: v.array(v.string()),
    /** True after we've used the cheap title model to produce a smart title. */
    titleAutoGenerated: v.optional(v.boolean()),
    /**
     * Thread-mode id from `@wikipefia/chat/modes`. `undefined` ⇒ implicit
     * "default" mode. Locked at thread creation; cannot be changed mid-thread
     * because old tool-call/result history may reference tools other modes
     * don't expose.
     */
    mode: v.optional(v.string()),
    /**
     * Resolved-snapshot of mode settings at thread creation time. We persist
     * the resolved values (with defaults applied) so later changes to a
     * mode's defaults don't retroactively alter old threads' behavior.
     */
    modeSettings: v.optional(v.any()),
    /**
     * The mode's `promptVersion` at thread creation time. Recorded so
     * debug-export replays know exactly which prompt produced which thread.
     */
    modePromptVersion: v.optional(v.string()),
    /**
     * Tutor-mode topic plan. Built by the model up-front (Phase 0 of the
     * tutor flow) via the `PlanTopics` tool, then optionally edited by the
     * user in the side panel before teaching begins.
     *
     * Stored as a JSON array (use `v.any()` to avoid migration churn while
     * the shape is iterating). Concrete TypeScript shape:
     *   { id: string, title: string, description: string, prompt: string,
     *     order: number, status: "pending" | "active" | "completed" | "skipped" }
     *
     * Undefined means "no plan yet". Empty array means "user removed all
     * topics" (treated like 'none' from the agent's perspective).
     */
    topicPlan: v.optional(v.any()),
    /**
     * High-level state of the tutor session. Drives the model's behavior
     * (which fragment of the system prompt is active) and the UI (which
     * widgets render in chat / which panel content shows on the side).
     *
     *   - "input"     — no plan yet; awaiting model's PlanTopics tool-call
     *   - "review"    — plan emitted, awaiting user's approval / edits
     *   - "teaching"  — user approved; model is teaching topic-by-topic
     *   - "completed" — all topics covered; session done
     *
     * Undefined = "input" (back-compat for tutor threads created before
     * this feature).
     */
    tutorPhase: v.optional(v.string()),
    /**
     * Monotonically-increasing token bumped each time a new generation starts
     * (sendMessage / editAndRegenerate / regenerateMessage). The runAgent
     * action remembers the value it was scheduled with and aborts if it sees
     * a newer value during polling — that way a clicked "regenerate" cleanly
     * supersedes any in-flight stream from the previous prompt without races.
     */
    generationId: v.optional(v.number()),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_user_updated", ["userId", "updatedAt"])
    .index("by_thread", ["threadId"]),

  /**
   * Side-channel storage for QuestionBox sub-conversations.
   *
   * QuestionBox is a widget the LLM places inline in its answers after
   * discrete subtopics. The user can click it to ask a focused follow-up
   * about that subtopic — without disturbing the main thread. Each follow-up
   * lives as a row here, anchored to the parent assistant message + the
   * QuestionBox tool-call id. We deliberately don't reuse the agent
   * component's thread machinery for these because:
   *   - the sub-conversation is text-only (no widgets, no approvals),
   *   - we want surgical control over the truncated parent context, and
   *   - the streamingMessages indirection of the agent component is
   *     overkill at the rate we patch a single accumulating text field.
   *
   * Status lifecycle: pending → streaming → complete | error.
   */
  questionBoxPairs: defineTable({
    /** Parent agent thread id this QuestionBox lives in. */
    parentThreadId: v.string(),
    /** Assistant message id whose content includes the QuestionBox tool-call. */
    parentMessageId: v.string(),
    /** The QuestionBox tool-call id — multiple QuestionBoxes per message ⇒
     *  this disambiguates which one this pair belongs to. */
    toolCallId: v.string(),
    /** Owner (anonymous session id). */
    userId: v.string(),
    /** The topic the LLM wrote into the QuestionBox's tool args, copied here
     *  so queries don't need to re-resolve the parent message. */
    topic: v.string(),
    /** 0-based position within this QuestionBox's Q&A history. Used to
     *  preserve order across multiple follow-ups. */
    ord: v.number(),
    /** What the user asked. */
    question: v.string(),
    /** Streamed answer text — patched (throttled) as the LLM produces deltas. */
    answer: v.string(),
    status: v.union(
      v.literal("pending"),
      v.literal("streaming"),
      v.literal("complete"),
      v.literal("error"),
    ),
    errorMessage: v.optional(v.string()),
    /** OpenRouter model id used for this answer. */
    model: v.optional(v.string()),
    createdAt: v.number(),
  })
    .index("by_tool_call_ord", ["toolCallId", "ord"])
    .index("by_user_thread", ["userId", "parentThreadId"]),
});
