import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

/**
 * Schema additions for Wikipefia Chat:
 *
 * - `threadMeta` — app-specific metadata for chat threads layered on top of
 *   what @convex-dev/agent stores: model id, system prompt version,
 *   soft-delete, cancel flag, unlocked widgets for tiered tool disclosure.
 *
 * The @convex-dev/agent component manages its own internal tables for
 * threads, messages, and stream deltas via the registered component — we
 * don't define those here.
 *
 * `userId` is the anonymous session id from the client (stored in
 * localStorage). It scopes a user's threads to their browser/device. There
 * is no auth — this is a v1 simplification; auth can be added later.
 */
export default defineSchema({
  // Existing app: projects (Wikipefia studio content registry)
  projects: defineTable({
    slug: v.string(),
    name: v.string(),
    description: v.string(),
    githubRepo: v.string(),
    branch: v.string(),
    type: v.union(
      v.literal("subject"),
      v.literal("teacher"),
      v.literal("system"),
    ),
    configJson: v.optional(v.any()),
    cachedTree: v.optional(
      v.array(
        v.object({
          path: v.string(),
          type: v.string(),
          sha: v.string(),
          size: v.optional(v.number()),
        }),
      ),
    ),
    lastSynced: v.optional(v.number()),
  })
    .index("by_slug", ["slug"])
    .index("by_type", ["type"])
    .index("by_github_repo", ["githubRepo"]),

  // Chat: per-thread metadata layered on top of @convex-dev/agent's threads
  threadMeta: defineTable({
    /** Foreign reference to the agent component's thread id (a string). */
    threadId: v.string(),
    /** Anonymous session id from the client (localStorage-stored UUID). */
    userId: v.string(),
    /** Display title — generated from first user message. */
    title: v.string(),
    /** Lifecycle status (UI hint). */
    status: v.union(
      v.literal("idle"),
      v.literal("generating"),
      v.literal("awaiting_user"),
      v.literal("error"),
    ),
    /** OpenRouter model id locked at thread creation. */
    modelId: v.string(),
    /** System prompt version used for this thread (for replay/debug). */
    systemPromptVersion: v.string(),
    /** Set by cancelGeneration mutation; checked by agent step to abort. */
    cancelRequested: v.boolean(),
    /** Soft-delete timestamp. */
    deletedAt: v.optional(v.number()),
    /** Widget names the model has unlocked via lookupWidgetDocs in this thread. */
    unlockedWidgets: v.array(v.string()),
    /** True after we've used the cheap title model to produce a smart title. */
    titleAutoGenerated: v.optional(v.boolean()),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_user_updated", ["userId", "updatedAt"])
    .index("by_thread", ["threadId"]),
});
